name: SorteringsAlgo
version: '${project.version}'
main: ntk.notekri.sorteringsalgo.SorteringsAlgo
commands:
  fuck:
    usage: /fuck
    description: Suck a fat one (._.)
  quicksort:
    usage: /quicksort
    description: Sorter lortet
  hanoi:
    usage: /hanoi
    description: Hanoi